config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
    }

  devise_scope :user do
    get "users", :to => "users/registrations#index"
    get "user/:id", :to => "users/registrations#show"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "edit", :to => "users/registrations#profile_edit"
    patch "update", :to => "users/registrations#profile_update"
  end

  resources :books do
    resources :impressions, :only => [:create, :destroy]
    resources :user_books
    get "history"
  end

  root 'books#index'

end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true

  has_many :impressions, dependent: :destroy
  has_many :users, through: :user_books
  has_many :user_books

  mount_uploader :img, ImgUploader
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true).page(params[:page]).per(10)
    @impressions_count = Impression.where(book_id: @q.id).count
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save!
     redirect_to "/"
    else
     render "new"
   end
  end

  def show
    @book = Book.find(params[:id])
    @impressions = @book.impressions
    @impression = Impression.new
    @user_books = @book.user_books
    @user_book = UserBook.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to "/"
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to "/"
  end

  def history
    @book = Book.find(params[:book_id])
    @user_books = @book.user_books
  end

   private

   def book_params
    params.require(:book).permit(:title, :description, :img)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_table_head.html.erb
<thead class="thead-dark">
  <tr>
    <th style="width: 40px">No.</th>
    <th style="width: 200px">タイトル</th>
    <th style="width: 100px">画像</th>
    <th style="width: 300px">説明</th>
    <th style="width: 50px">感想数</th>
    <th style="width: 180px">登録日時</th>
    <th style="width: 180px">更新日時</th>
    <th style="width: 50px">貸借ステータス</th>
    <th style="width: 100px"></th>
  </tr>
</thead>

app/views/books/edit.html.erb
<h1>編集</h1>

<div class="table_margin">
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
    <%= render "table_head" %>
    <tbody style="background-color: white;">
      <tr>
      <%= form_for @book do |f| %>
        <td><%= @book.id %></td>
        <td><%= f.text_field :title, value: @book.title %></td>
        <td><%= f.file_field :img, class: "image" %></td>
        <td><%= f.text_area :description, value: @book.description %></td>
        <td><%= Impression.where(book_id: @book.id).count %></td>
        <td><%= @book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        <td><%= @book.updated_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        <td>
          <% if UserBook.where(book_id: @book.id).blank? %>
            <p>誰も借りてない</p>
          <% elsif UserBook.where(book_id: @book.id).last.status == "lend" %>
            <p>借りれる</p>
          <% elsif UserBook.where(book_id: @book.id).last.status == "borrow" %>
            <p>貸し出し中</p>
          <% end %>
        </td>
        <td>
          <%= link_to '詳細', @book, class: "btn btn-primary" %>
          <%= f.submit "更新", class: "btn btn-primary" %>
          <%= link_to '削除', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/books/history.html.erb
<h1>履歴</h1>

<div class="table_margin">
  <%= @book.title %>
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
    <thead>
      <tr>
        <th>created_at</th>
        <th>status</th>
        <th>user_name</th>
      </tr>
    </thead>
    <tbody style="background-color: white;">
    <% @user_books.each do |user_book| %>
      <tr>
        <td><%= user_book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        <td><%= user_book.status %></td>
        <td><%= user_book.user.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/books/index.html.erb
<div class="d-flex align-items-center"  style="margin: 70px 0px 0px 50px;" >
  <h1>Books一覧</h1>
  <a class="btn btn-primary" href="/books/new" role="button" style="margin: 30px 10px 10px 30px;">Book登録</a>
</div>

<div class="search_form">
  <%= search_form_for @q do |f| %>
    <%= f.label :title, "タイトル検索" %>
    <%= f.search_field :title_cont %>
    <%= f.submit "検索" %>
  <% end %>
</div>

<div class="paginate">
  <%= paginate @books %>
</div>

<div class="table_margin">
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
    <%= render "table_head" %>
    <tbody style="background-color: white;">
      <% @books.each do |book| %>
        <% if UserBook.where(book_id: book.id).blank? %>
        <tr class="success">
          <td><%= book.id %></td>
          <td><%= link_to book.title, book %></td>
          <td>
            <% if book.img? %>
              <%= image_tag book.img.url %>
            <% else %>
              <%= image_tag "default.jpg" %>
            <% end %>
          </td>
          <td><%= book.description.truncate(150) %></td>
          <td><%= Impression.where(book_id: book.id).count %></td>
          <td><%= book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><%= book.updated_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><p>誰も借りてない</p></td>
          <td>
            <%= link_to '編集', edit_book_path(book), class: "btn btn-primary" %>
            <%= link_to '削除', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
        </tr>
        <% elsif UserBook.where(book_id: book.id).last.status == "lend" %>
        <tr class="success">
          <td><%= book.id %></td>
          <td><%= link_to book.title, book %></td>
          <td>
            <% if book.img? %>
              <%= image_tag book.img.url %>
            <% else %>
              <%= image_tag "default.jpg" %>
            <% end %>
          </td>
          <td><%= book.description.truncate(150) %></td>
          <td><%= Impression.where(book_id: book.id).count %></td>
          <td><%= book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><%= book.updated_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><p>借りれる</p></td>
          <td>
            <%= link_to '編集', edit_book_path(book), class: "btn btn-primary" %>
            <%= link_to '削除', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
        </tr>
        <% elsif UserBook.where(book_id: book.id).last.status == "borrow" && UserBook.where(book_id: book.id).last.user == current_user %>
        <tr class="danger">
          <td><%= book.id %></td>
          <td><%= link_to book.title, book %></td>
          <td>
            <% if book.img? %>
              <%= image_tag book.img.url %>
            <% else %>
              <%= image_tag "default.jpg" %>
            <% end %>
          </td>
          <td><%= book.description.truncate(150) %></td>
          <td><%= Impression.where(book_id: book.id).count %></td>
          <td><%= book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><%= book.updated_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><p>貸し出し中</p>(<%= link_to book.user_books.last.user.name, "/user/#{book.user_books.last.user.id}" %>)</td>
          <td>
            <%= link_to '編集', edit_book_path(book), class: "btn btn-primary" %>
            <%= link_to '削除', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
        </tr>
        <% elsif UserBook.where(book_id: book.id).last.status == "borrow" %>
        <tr class="bg-secondary text-white">
          <td><%= book.id %></td>
          <td><%= link_to book.title, book %></td>
          <td>
            <% if book.img? %>
              <%= image_tag book.img.url %>
            <% else %>
              <%= image_tag "default.jpg" %>
            <% end %>
          </td>
          <td><%= book.description.truncate(150) %></td>
          <td><%= Impression.where(book_id: book.id).count %></td>
          <td><%= book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><%= book.updated_at.strftime("%Y年%m月%d日 %H:%M") %></td>
          <td><p>貸し出し中</p>(<%= link_to book.user_books.last.user.name, "/user/#{book.user_books.last.user.id}" %>)</td>
          <td>
            <%= link_to '編集', edit_book_path(book), class: "btn btn-primary" %>
            <%= link_to '削除', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<h1>新規登録</h1>

<table class="table table-bordered border-primary table-hover table-sm posts_table">
<%= form_for @book do |f| %>
<thead class="thead-dark">
  <tr>
    <th style="width: 200px"><%= f.label :title, 'タイトル' %></th>
    <th style="width: 300px"><%= f.label :content, '投稿内容' %></th>
  </tr>
</thead>
<tbody>
  <tr>
    <th><%= f.text_field :title %></th>
    <th><%= f.text_area :description %></th>
  </tr>
<tbody>

</table>
<%= f.submit '登録', class: "btn btn-primary" %>
<% end %>

app/views/books/show.html.erb
<h1>詳細</h1>

<div class="table_margin">
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
    <%= render "table_head" %>
    <tbody style="background-color: white;">
      <tr>
        <td><%= @book.id %></td>
        <td><%= @book.title %></td>
        <td>
          <% if @book.img? %>
            <%= image_tag @book.img.url %>
          <% else %>
            <%= image_tag "default.jpg" %>
          <% end %>
        </td>
        <td><%= @book.description %></td>
        <td><%= Impression.where(book_id: @book.id).count %></td>
        <td><%= @book.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        <td><%= @book.updated_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        <td>
          <% if UserBook.where(book_id: @book.id).blank? %>
            <p>誰も借りてない</p>
          <% elsif UserBook.where(book_id: @book.id).last.status == "lend" %>
            <p>借りれる</p>
          <% elsif UserBook.where(book_id: @book.id).last.status == "borrow" %>
            <p>貸し出し中</p>
          <% end %>
        </td>
        <td>
          <%= link_to '編集', edit_book_path(@book), class: "btn btn-primary" %>
          <%= link_to '削除', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    </tbody>
  </table>

  <h2>貸し出し</h2>
  <%= form_for [@book, @user_book] do |f| %>
    <% if @book.user_books.blank? %>
      <%= f.select :status, [["借りる", "borrow"],["返す", "lend"]] %>
      <%= f.submit '投稿' %>
    <% elsif @book.user_books.last.status == "borrow" %>
      <%= f.select :status, [["借りる", "borrow"],["返す", "lend"]] %>
      <%= f.submit '投稿' %>
      <p>借りてる人:<%= @book.user_books.last.user.name %></p>
    <% elsif @book.user_books.last.status == "lend"  %>
      <%= f.select :status, [["借りる", "borrow"],["返す", "lend"]] %>
      <%= f.submit '投稿' %>
    <% end %>
  <% end %>
  <%= link_to '貸し出し履歴', book_history_path(@book), class: "btn btn-primary" %>

  <h2>感想一覧</h2>
  <%= form_for [@book, @impression] do |f| %>
    <%= f.text_area :content, onkeyup: "ShowLength(value);" %>
    <p id="inputlength">0文字(50文字まで)</p>
    <%= f.submit '投稿する' %>
  <% end %>
  <table class="table table-bordered border-primary table-hover table-sm posts_table">
    <thead>
      <tr>
        <th>id</th>
        <th>内容</th>
        <th>投稿者</th>
        <th>投稿日時</th>
      </tr>
    </thead>
    <tbody style="background-color: white;">
      <% @impressions.each do |i| %>
        <tr>
          <td><%= i.id  %></td>
          <td><%= i.content %></td>
          <td><%= link_to i.user.name, "/user/#{i.user.id}" %></td>
          <td><%= i.created_at.strftime("%Y年%m月%d日 %H:%M") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  function ShowLength(str) {
    var inputLength = document.getElementById("inputlength")

    if (str.length < 50) {
      inputLength.innerHTML = str.length + "文字"
      inputlength.style.color = "green";
    } else {
      {
        inputLength.innerHTML = str.length + "文字"
        inputlength.style.color = "red";
      }
    }
  }
</script>